# -*- coding: utf-8 -*-
"""Mock_Data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aC9ra2XfBsLk4oPpG6X7OW4_X8veccqZ

1. สร้าง Customer Master (ลูกค้า 500 คน)
"""

N_CUSTOMERS = 500
customer_df = pd.DataFrame({
    "customer_id": [f"C{str(i).zfill(4)}" for i in range(1, N_CUSTOMERS + 1)],
    "gender": np.random.choice(["M", "F"], size=N_CUSTOMERS, p=[0.45, 0.55]),
    "true_segment": np.random.choice(["Champion", "Loyal", "At-Risk", "New"], size=N_CUSTOMERS, p=[0.20, 0.30, 0.25, 0.25])
})
print(f"✅ สร้างข้อมูลลูกค้าหลักสำเร็จ: {customer_df.shape[0]} คน")
display(customer_df.head())

"""2. สร้าง Promotion Master (10 แคมเปญ)"""

promo_df = pd.DataFrame({
    "promotion_id": [
        "P_NEWYEAR", "P_MIDYEAR", "P_FLASH", "P_CHAMPION", "P_LOYAL",
        "P_WELCOME", "P_WINBACK", "P_PAYDAY", "P_DOUBLE_SALE", "P_WEEKEND"
    ],
    "promo_type": [
        "percent_discount", "fixed_discount", "percent_discount", "percent_discount", "percent_discount",
        "fixed_discount", "percent_discount", "fixed_discount", "percent_discount", "fixed_discount"
    ],
    "discount_value": [10, 200, 15, 20, 15, 100, 25, 50, 12, 30],
    "start_date": [
        datetime(2023, 12, 15), datetime(2024, 6, 1), datetime(2024, 3, 1), datetime(2024, 1, 1), datetime(2024, 1, 1),
        datetime(2024, 1, 1), datetime(2024, 1, 1), datetime(2024, 1, 25), datetime(2024, 4, 1), datetime(2024, 1, 1)
    ],
    "end_date": [
        datetime(2024, 1, 15), datetime(2024, 6, 30), datetime(2024, 3, 3), datetime(2024, 12, 31), datetime(2024, 12, 31),
        datetime(2024, 12, 31), datetime(2024, 12, 31), datetime(2024, 12, 31), datetime(2024, 4, 7), datetime(2024, 12, 31)
    ],
    "target_segment": ["All", "All", "All", "Champion", "Loyal", "New", "At-Risk", "All", "All", "All"]
})
print(f"✅ สร้างตารางโปรโมชันหลักสำเร็จ: {promo_df.shape[0]} แคมเปญ")
display(promo_df)

"""3. สร้าง Sales Transaction (ประวัติการซื้อ)"""

segment_behavior = {
    "Champion": {"freq_range": (8, 20), "spend_range": (500, 3000)},
    "Loyal": {"freq_range": (5, 12), "spend_range": (200, 1000)},
    "At-Risk": {"freq_range": (1, 4), "spend_range": (100, 400)},
    "New": {"freq_range": (1, 3), "spend_range": (50, 200)}
}

transactions_list = []
for _, customer in customer_df.iterrows():
    c_id = customer["customer_id"]
    seg = customer["true_segment"]
    behavior = segment_behavior[seg]

    n_transactions = np.random.randint(*behavior["freq_range"])

    for i in range(n_transactions):
        days_offset = np.random.randint(0, 180)
        txn_date = datetime(2024, 1, 1) + timedelta(days=days_offset)
        subtotal = round(np.random.uniform(*behavior["spend_range"]), 2)

        # 🌟 สอดไส้ความสมจริง: สุ่มเกิด Outlier 2.5%
        if np.random.random() < 0.025:
            multiplier = np.random.uniform(5, 12)
            subtotal = round(subtotal * multiplier, 2)

        used_promo = "NONE"
        discount_amount = 0

        active_promos = promo_df[
            (promo_df["start_date"] <= txn_date) &
            (promo_df["end_date"] >= txn_date) &
            ((promo_df["target_segment"] == "All") | (promo_df["target_segment"] == seg))
        ]

        if len(active_promos) > 0 and np.random.random() < 0.40:
            promo = active_promos.sample(1).iloc[0]
            used_promo = promo["promotion_id"]
            if promo["promo_type"] == "percent_discount":
                discount_amount = round(subtotal * promo["discount_value"] / 100, 2)
            elif promo["promo_type"] == "fixed_discount":
                discount_amount = min(promo["discount_value"], subtotal)

        final_amount = round(subtotal - discount_amount, 2)

        transactions_list.append({
            "transaction_id": f"T{len(transactions_list) + 1:06d}",
            "customer_id": c_id,
            "transaction_date": txn_date.strftime("%Y-%m-%d"),
            "subtotal": subtotal,
            "promotion_id": used_promo,
            "final_amount": final_amount
        })

sales_df = pd.DataFrame(transactions_list)
print(f"✅ สร้างข้อมูลยอดขายดิบสำเร็จ: {sales_df.shape[0]:,} รายการ")
display(sales_df.head())

"""แปลงตารางเป็นแนวกว้าง (Wide Format สำหรับใส่สไลด์พรีเซนต์)"""

eng_months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
demo_customer_df = pd.DataFrame({
    "customer_id": ["C0001", "C0042"],
    "true_segment": ["Champion", "At-Risk"]
})

demo_segment_behavior = {
    "Champion": {"freq_range": (2, 5), "spend_range": (1000, 3000)},
    "At-Risk": {"freq_range": (1, 2), "spend_range": (100, 500)}
}

demo_list = []
for _, customer in demo_customer_df.iterrows():
    c_id = customer["customer_id"]
    seg = customer["true_segment"]
    behavior = demo_segment_behavior[seg]
    n_transactions = np.random.randint(*behavior["freq_range"])

    for i in range(n_transactions):
        days_offset = np.random.randint(0, 180)
        txn_date = datetime(2024, 1, 1) + timedelta(days=days_offset)
        subtotal = round(np.random.uniform(*behavior["spend_range"]), 2)

        month_str = eng_months[txn_date.month - 1]
        detail_text = f"฿{subtotal:,.0f} on {month_str} {txn_date.day}"

        demo_list.append({
            "customer_id": c_id,
            "true_segment": seg,
            "transaction_no": f"Transaction {i+1}",
            "detail": detail_text
        })

demo_txn_df = pd.DataFrame(demo_list)
example_df = demo_txn_df.pivot(index=["customer_id", "true_segment"], columns="transaction_no", values="detail").reset_index()
example_df = example_df.fillna("—")
example_df.columns.name = None

print("Expected Output (ตารางตัวอย่างแนวกว้างในสไลด์):")
display(example_df)

# -*- coding: utf-8 -*-
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import os

# ตั้งค่า Seed เพื่อความแม่นยำทางสถิติ (รันกี่ครั้งก็ได้เลขเดิม)
np.random.seed(42)

print("============ [Step 1] สร้าง Customer Master ============")
N_CUSTOMERS = 500
customer_df = pd.DataFrame({
    "customer_id": [f"C{str(i).zfill(4)}" for i in range(1, N_CUSTOMERS + 1)],
    "gender": np.random.choice(["M", "F"], size=N_CUSTOMERS, p=[0.45, 0.55]),
    "true_segment": np.random.choice(["Champion", "Loyal", "At-Risk", "New"], size=N_CUSTOMERS, p=[0.20, 0.30, 0.25, 0.25])
})
print(f"✅ สร้างข้อมูลลูกค้าหลักสำเร็จ: {customer_df.shape[0]} คน")
display(customer_df.head())


print("\n============ [Step 2] สร้าง Promotion Master (10 แคมเปญ) ============")
promo_df = pd.DataFrame({
    "promotion_id": [
        "P_NEWYEAR", "P_MIDYEAR", "P_FLASH", "P_CHAMPION", "P_LOYAL",
        "P_WELCOME", "P_WINBACK", "P_PAYDAY", "P_DOUBLE_SALE", "P_WEEKEND"
    ],
    "promo_type": [
        "percent_discount", "fixed_discount", "percent_discount", "percent_discount", "percent_discount",
        "fixed_discount", "percent_discount", "fixed_discount", "percent_discount", "fixed_discount"
    ],
    "discount_value": [10, 200, 15, 20, 15, 100, 25, 50, 12, 30],
    "start_date": [
        datetime(2023, 12, 15), datetime(2024, 6, 1), datetime(2024, 3, 1), datetime(2024, 1, 1), datetime(2024, 1, 1)
    ],
    "end_date": [
        datetime(2024, 1, 15), datetime(2024, 6, 30), datetime(2024, 3, 3), datetime(2024, 12, 31), datetime(2024, 12, 31)
    ],
    "target_segment": ["All", "All", "All", "Champion", "Loyal", "New", "At-Risk", "All", "All", "All"]
})
# เติมข้อมูลวันที่ส่วนที่เหลือให้เต็มตาราง 10 แคมเปญ
promo_df.loc[5:, 'start_date'] = datetime(2024, 1, 1)
promo_df.loc[5:, 'end_date'] = datetime(2024, 12, 31)
print(f"✅ สร้างตารางโปรโมชันหลักสำเร็จ: {promo_df.shape[0]} แคมเปญ")
display(promo_df)


print("\n============ [Step 3] สร้าง Sales Transaction (ข้อมูลดิบระบบ Long Format) ============")
segment_behavior = {
    "Champion": {"freq_range": (8, 20), "spend_range": (500, 3000)},
    "Loyal": {"freq_range": (5, 12), "spend_range": (200, 1000)},
    "At-Risk": {"freq_range": (1, 4), "spend_range": (100, 400)},
    "New": {"freq_range": (1, 3), "spend_range": (50, 200)}
}

transactions_list = []
for _, customer in customer_df.iterrows():
    c_id = customer["customer_id"]
    seg = customer["true_segment"]
    behavior = segment_behavior[seg]

    n_transactions = np.random.randint(*behavior["freq_range"])

    for i in range(n_transactions):
        days_offset = np.random.randint(0, 180)
        txn_date = datetime(2024, 1, 1) + timedelta(days=days_offset)
        subtotal = round(np.random.uniform(*behavior["spend_range"]), 2)

        # 🌟 สอดไส้ความสมจริง: สุ่มเกิด Outlier 2.5% (บิลเหมาล็อตใหญ่)
        if np.random.random() < 0.025:
            multiplier = np.random.uniform(5, 12)
            subtotal = round(subtotal * multiplier, 2)

        used_promo = "NONE"
        discount_amount = 0

        active_promos = promo_df[
            (promo_df["start_date"] <= txn_date) &
            (promo_df["end_date"] >= txn_date) &
            ((promo_df["target_segment"] == "All") | (promo_df["target_segment"] == seg))
        ]

        if len(active_promos) > 0 and np.random.random() < 0.40:
            promo = active_promos.sample(1).iloc[0]
            used_promo = promo["promotion_id"]
            if promo["promo_type"] == "percent_discount":
                discount_amount = round(subtotal * promo["discount_value"] / 100, 2)
            elif promo["promo_type"] == "fixed_discount":
                discount_amount = min(promo["discount_value"], subtotal)

        final_amount = round(subtotal - discount_amount, 2)

        transactions_list.append({
            "transaction_id": f"T{len(transactions_list) + 1:06d}",
            "customer_id": c_id,
            "transaction_date": txn_date.strftime("%Y-%m-%d"),
            "subtotal": subtotal,
            "promotion_id": used_promo,
            "final_amount": final_amount
        })

sales_df = pd.DataFrame(transactions_list)
print(f"✅ สร้างข้อมูลยอดขายดิบสำเร็จ: {sales_df.shape[0]:,} รายการ")
display(sales_df.head())


print("\n============ [Step 4] ตัวอย่างการแปลงตารางเป็นแนวกว้าง (Wide Format Example) ============")
# 💡 แก้ไขจุดบั๊ก: ใช้ชื่อตัวแปรเฉพาะเจาะจง (Demo) เพื่อไม่ให้ไปเซฟทับตัวแปรหลักด้านบน
eng_months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
demo_customer_df = pd.DataFrame({
    "customer_id": ["C0001", "C0042"],
    "true_segment": ["Champion", "At-Risk"]
})

demo_segment_behavior = {
    "Champion": {"freq_range": (2, 5), "spend_range": (1000, 3000)},
    "At-Risk": {"freq_range": (1, 2), "spend_range": (100, 500)}
}

demo_list = []
for _, customer in demo_customer_df.iterrows():
    c_id = customer["customer_id"]
    seg = customer["true_segment"]
    behavior = demo_segment_behavior[seg]
    n_transactions = np.random.randint(*behavior["freq_range"])

    for i in range(n_transactions):
        days_offset = np.random.randint(0, 180)
        txn_date = datetime(2024, 1, 1) + timedelta(days=days_offset)
        subtotal = round(np.random.uniform(*behavior["spend_range"]), 2)

        month_str = eng_months[txn_date.month - 1]
        detail_text = f"฿{subtotal:,.0f} on {month_str} {txn_date.day}"

        demo_list.append({
            "customer_id": c_id,
            "true_segment": seg,
            "transaction_no": f"Transaction {i+1}",
            "detail": detail_text
        })

demo_txn_df = pd.DataFrame(demo_list)
example_df = demo_txn_df.pivot(index=["customer_id", "true_segment"], columns="transaction_no", values="detail").reset_index()
example_df = example_df.fillna("—")
example_df.columns.name = None

print("Expected Output (ตารางตัวอย่างแนวกว้างในสไลด์):")
display(example_df)


print("\n============ [Step 5] บันทึกไฟล์ลงโฟลเดอร์ และรายงานผลลัพธ์สุทธิ ============")
os.makedirs("data/raw", exist_ok=True)
customer_df.to_csv("data/raw/customer_master.csv", index=False)
promo_df.to_csv("data/raw/promotion_master.csv", index=False)
sales_df.to_csv("data/raw/sales_transaction.csv", index=False)

print("✅ รวมร่างและอัปเดตระบบสุ่มข้อมูลเสร็จสิ้น!")
print(f"• ตรวจสอบจำนวนลูกค้าในตารางเซฟจริง: {customer_df.shape[0]} คน (กลับมาครบ 500 คนอย่างถูกต้อง! 🎉)")
print(f"• ตรวจสอบจำนวนยอดขายทั้งหมด: {sales_df.shape[0]:,} รายการ")
print(f"• ยอดขายสูงสุดจริงในร้านที่ติดสลัก Outlier: ฿{sales_df['final_amount'].max():,.2f} บาท")
print(f"📁 รายชื่อไฟล์ที่จัดเก็บใน data/raw/ : {os.listdir('data/raw')}")

"""4. ส่วนแสดงผลลัพธ์หลังรันสำเร็จ (Show Output)"""

print("✅ รวมร่างและอัปเดตระบบสุ่มข้อมูลเสร็จสิ้น!")
print(f"• ตรวจสอบจำนวนลูกค้า: {customer_df.shape[0]} คน")
print(f"• ตรวจสอบจำนวนยอดขายทั้งหมด: {sales_df.shape[0]:,} รายการ")
print(f"• ยอดขายสูงสุดที่เกิดขึ้นในร้าน (Outlier): ฿{sales_df['final_amount'].max():,.2f} บาท")

# โหลดไฟล์ยอดขายมาตรวจสอบ
df_sales = pd.read_csv("data/raw/sales_transaction.csv")

print("ขนาดของตารางยอดขาย (แถว, คอลัมน์):", df_sales.shape)
print("\nตัวอย่างข้อมูลยอดขาย 5 แถวแรก:")
display(df_sales.head())

"""5. บันทึกไฟล์ทั้งหมดลงโฟลเดอร์ data/raw"""

os.makedirs("data/raw", exist_ok=True)
customer_df.to_csv("data/raw/customer_master.csv", index=False)
promo_df.to_csv("data/raw/promotion_master.csv", index=False)
sales_df.to_csv("data/raw/sales_transaction.csv", index=False)

customer_df.to_csv("data/raw/customer_master.csv", index=False)
# index=False = ไม่บันทึก index (0, 1, 2, ...) เป็น column
# ถ้าลืมใส่ จะมี column "Unnamed: 0" โผล่มาใน CSV