# -*- coding: utf-8 -*-
"""mock_data

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zHYnTpdSCb2DM1CKoQyuKbPB8TDoQ7Fa
"""

import numpy as np
import pandas as pd
import random

np.random.seed(42)
random.seed(42)

"""สร้าง Customer Master"""

N_CUSTOMERS = 500

# สร้างทีละ column แล้วรวมเป็น DataFrame
customer_df = pd.DataFrame({
    "customer_id": [f"C{str(i).zfill(4)}" for i in range(1, 501)],
    # C0001, C0002, ... C0500
    # zfill(4) = เติม 0 ข้างหน้าให้ครบ 4 หลัก

    "gender": np.random.choice(["M", "F"], size=500, p=[0.45, 0.55]),
    # p=[0.45, 0.55] = กำหนดความน่าจะเป็น 45% ชาย 55% หญิง
    # ถ้าไม่ใส่ p จะ 50/50

    "true_segment": np.random.choice(
        ["Champion", "Loyal", "At-Risk", "New"],
        size=500,
        p=[0.20, 0.30, 0.25, 0.25]
        # Champion 20%, Loyal 30%, At-Risk 25%, New 25%
    ),
})

"""สร้าง Transaction ตาม Segment Behavior"""

# กำหนดพฤติกรรมของแต่ละ segment
segment_behavior = {
    "Champion": {"freq_range": (8, 20),  "spend_range": (500, 3000)}, #Champion จะซื้อ 8-20 ครั้งใน 6 เดือน และแต่ละ transaction ใช้จ่าย 500-3,000 บาท
    "Loyal":    {"freq_range": (5, 12),  "spend_range": (200, 1000)},
    "At-Risk":  {"freq_range": (1, 4),   "spend_range": (100, 400)},
    "New":      {"freq_range": (1, 3),   "spend_range": (50, 200)},
}

"""loop สร้าง transaction ต่อลูกค้าแต่ละคน"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# 1. เปลี่ยนชื่อเดือนเป็นตัวย่อภาษาอังกฤษ
eng_months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]

# กำหนดพฤติกรรมของแต่ละ Segment
segment_behavior = {
    "Champion": {"freq_range": (2, 5), "spend_range": (1000, 3000)},
    "Loyal": {"freq_range": (2, 4), "spend_range": (800, 2000)},
    "At-Risk": {"freq_range": (1, 2), "spend_range": (100, 500)},
    "New": {"freq_range": (1, 2), "spend_range": (200, 1000)}
}

# สมมติ customer_df
customer_df = pd.DataFrame({
    "customer_id": ["C0001", "C0042"],
    "true_segment": ["Champion", "At-Risk"]
})

transactions_list = []

# 2. เริ่มลอจิกการสุ่ม
for _, customer in customer_df.iterrows():
    c_id = customer["customer_id"]
    seg = customer["true_segment"]
    behavior = segment_behavior[seg]

    # จำนวนครั้งที่ซื้อ - random จาก range
    n_transactions = np.random.randint(*behavior["freq_range"])

    for i in range(n_transactions):
        # สุ่มวันที่ซื้อ ช่วง 6 เดือน
        days_offset = np.random.randint(0, 180)
        txn_date = datetime(2024, 1, 1) + timedelta(days=days_offset)

        # สุ่มยอดซื้อ
        subtotal = round(np.random.uniform(*behavior["spend_range"]), 2)

        # จัดฟอร์แมตข้อความให้ออกมาเป็นภาษาอังกฤษ เช่น "฿1,250 on Jan 15"
        month_str = eng_months[txn_date.month - 1]
        detail_text = f"฿{subtotal:,.0f} on {month_str} {txn_date.day}"

        transactions_list.append({
            "customer_id": c_id,
            "true_segment": seg,
            "transaction_no": f"Transaction {i+1}", # เปลี่ยนเป็นภาษาอังกฤษ
            "detail": detail_text
        })

# 3. แปลงเป็นตาราง DataFrame
txn_df = pd.DataFrame(transactions_list)

# 4. แปลงตารางให้อยู่ในรูปแนวกว้าง (Wide format)
example_df = txn_df.pivot(
    index=["customer_id", "true_segment"],
    columns="transaction_no",
    values="detail"
).reset_index()

# เติมเครื่องหมายขีด (-) ในช่องที่ว่าง และลบชื่อแกน column ทิ้ง
example_df = example_df.fillna("—")
example_df.columns.name = None

print("Expected Output:")
display(example_df)

"""เพิ่ม Promotion Logic

"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta

# ==========================================
# ส่วนที่ 1: สร้างข้อมูลตั้งต้น (Mock Data)
# ==========================================

# 1.1 สร้างตารางลูกค้า
customer_df = pd.DataFrame({
    "customer_id": ["C0001", "C0042", "C0099"],
    "true_segment": ["Champion", "At-Risk", "Loyal"]
})

# 1.2 สร้างตารางโปรโมชั่น
promo_df = pd.DataFrame({
    "promotion_id": ["P_NEWYEAR", "P_MIDYEAR", "P_FLASH", "P_CHAMPION"],
    "promo_type": ["percent_discount", "fixed_discount", "percent_discount", "percent_discount"],
    "discount_value": [10, 200, 15, 20], # 10%, ลด 200 บาท, 15%, 20%
    "start_date": [datetime(2023, 12, 15), datetime(2024, 6, 1), datetime(2024, 3, 1), datetime(2024, 1, 1)],
    "end_date": [datetime(2024, 1, 15), datetime(2024, 6, 30), datetime(2024, 3, 3), datetime(2024, 12, 31)],
    "target_segment": ["All", "All", "All", "Champion"]
})

# 1.3 กำหนดพฤติกรรมลูกค้า (เหมือนเดิม)
segment_behavior = {
    "Champion": {"freq_range": (2, 5), "spend_range": (1000, 3000)},
    "Loyal": {"freq_range": (2, 4), "spend_range": (800, 2000)},
    "At-Risk": {"freq_range": (1, 2), "spend_range": (100, 500)},
    "New": {"freq_range": (1, 2), "spend_range": (200, 1000)}
}

# ==========================================
# ส่วนที่ 2: สร้างลูปจำลองการซื้อและการใช้โปร
# ==========================================

transactions_list = []

for _, customer in customer_df.iterrows():
    c_id = customer["customer_id"]
    seg = customer["true_segment"]
    behavior = segment_behavior[seg]

    # สุ่มจำนวนครั้งที่ซื้อ
    n_transactions = np.random.randint(*behavior["freq_range"])

    for i in range(n_transactions):
        # สุ่มวันที่ซื้อ (ใช้ปี 2024 เป็นหลักเพื่อให้ตรงกับช่วงโปรโมชั่นจำลอง)
        days_offset = np.random.randint(0, 180)
        txn_date = datetime(2024, 1, 1) + timedelta(days=days_offset)

        # สุ่มยอดซื้อ
        subtotal = round(np.random.uniform(*behavior["spend_range"]), 2)

        # --- เริ่มลอจิกการใช้โปรโมชั่น ---
        used_promo = "None"
        discount_amount = 0

        # หาโปรที่ active ในวันที่ทำ transaction
        active_promos = promo_df[
            (promo_df["start_date"] <= txn_date) &
            (promo_df["end_date"] >= txn_date) &
            ((promo_df["target_segment"] == "All") | (promo_df["target_segment"] == seg))
        ]

        # โอกาส 40% ที่ลูกค้าจะใช้โปร
        if len(active_promos) > 0 and np.random.random() < 0.40:
            promo = active_promos.sample(1).iloc[0]
            used_promo = promo["promotion_id"]

            # คำนวณส่วนลดตามประเภทของโปร
            if promo["promo_type"] == "percent_discount":
                discount_amount = round(subtotal * promo["discount_value"] / 100, 2)
            elif promo["promo_type"] == "fixed_discount":
                discount_amount = min(promo["discount_value"], subtotal)
        # -----------------------------------------------

        # สรุปยอดสุทธิ (Net Amount)
        net_amount = subtotal - discount_amount

        # เก็บข้อมูลลงตาราง
        transactions_list.append({
            "customer_id": c_id,
            "segment": seg,
            "transaction_date": txn_date.strftime("%Y-%m-%d"),
            "subtotal": subtotal,
            "promo_used": used_promo,
            "discount": discount_amount,
            "net_amount": net_amount
        })

# ==========================================
# ส่วนที่ 3: แสดงผลลัพธ์
# ==========================================

final_sales_df = pd.DataFrame(transactions_list)

print("✅ สร้างตาราง Transaction (Long Format) สำเร็จแล้ว!")
print("สังเกตคอลัมน์ promo_used ว่ามีการสุ่มใช้โปรและคำนวณส่วนลดให้เรียบร้อย:\n")
display(final_sales_df.head(10))

"""บันทึก CSV"""

import os

# 1. สั่งให้ Colab สร้างโฟลเดอร์เตรียมไว้ก่อน (exist_ok=True แปลว่าถ้ามีโฟลเดอร์อยู่แล้วก็ไม่ต้องสร้างซ้ำ)
os.makedirs("data/raw", exist_ok=True)

# 2. บันทึกไฟล์ CSV ตามความหมายเดิมของคุณเป๊ะๆ
customer_df.to_csv("data/raw/customer_master.csv", index=False)

print("✅ สร้างโฟลเดอร์และบันทึกไฟล์ CSV สำเร็จแล้ว!")

customer_df.to_csv("data/raw/customer_master.csv", index=False)
# index=False = ไม่บันทึก index (0, 1, 2, ...) เป็น column
# ถ้าลืมใส่ จะมี column "Unnamed: 0" โผล่มาใน CSV

# 1. บันทึกตารางโปรโมชั่น
promo_df.to_csv("data/raw/promotion_master.csv", index=False)

# 2. บันทึกตารางยอดขาย (Transaction)
final_sales_df.to_csv("data/raw/sales_transaction.csv", index=False)

print("✅ บันทึกไฟล์ครบทั้ง 3 ตารางแล้ว!")
print("ตอนนี้ในโฟลเดอร์ data/raw จะมีไฟล์:")
import os
print(os.listdir("data/raw"))

"""รวมร่าง (แก้ปัญหาตัวแปรโดนเขียนทับ)"""

import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import os

# ==========================================
# 1. สร้าง Customer Master (ลูกค้า 500 คน)
# ==========================================
N_CUSTOMERS = 500
customer_df = pd.DataFrame({
    "customer_id": [f"C{str(i).zfill(4)}" for i in range(1, N_CUSTOMERS + 1)],
    "gender": np.random.choice(["M", "F"], size=N_CUSTOMERS, p=[0.45, 0.55]),
    "true_segment": np.random.choice(["Champion", "Loyal", "At-Risk", "New"], size=N_CUSTOMERS, p=[0.20, 0.30, 0.25, 0.25])
})

# ==========================================
# 2. สร้าง Promotion Master (4 แคมเปญ)
# ==========================================
promo_df = pd.DataFrame({
    "promotion_id": ["P_NEWYEAR", "P_MIDYEAR", "P_FLASH", "P_CHAMPION"],
    "promo_type": ["percent_discount", "fixed_discount", "percent_discount", "percent_discount"],
    "discount_value": [10, 200, 15, 20],
    "start_date": [datetime(2023, 12, 15), datetime(2024, 6, 1), datetime(2024, 3, 1), datetime(2024, 1, 1)],
    "end_date": [datetime(2024, 1, 15), datetime(2024, 6, 30), datetime(2024, 3, 3), datetime(2024, 12, 31)],
    "target_segment": ["All", "All", "All", "Champion"]
})

# ==========================================
# 3. สร้าง Sales Transaction (ประวัติการซื้อ)
# ==========================================
segment_behavior = {
    "Champion": {"freq_range": (8, 20), "spend_range": (500, 3000)},
    "Loyal": {"freq_range": (5, 12), "spend_range": (200, 1000)},
    "At-Risk": {"freq_range": (1, 4), "spend_range": (100, 400)},
    "New": {"freq_range": (1, 3), "spend_range": (50, 200)}
}

transactions_list = []
for _, customer in customer_df.iterrows():
    c_id = customer["customer_id"]
    seg = customer["true_segment"]
    behavior = segment_behavior[seg]

    n_transactions = np.random.randint(*behavior["freq_range"])

    for i in range(n_transactions):
        days_offset = np.random.randint(0, 180)
        txn_date = datetime(2024, 1, 1) + timedelta(days=days_offset)
        subtotal = round(np.random.uniform(*behavior["spend_range"]), 2)

        used_promo = "None"
        discount_amount = 0

        active_promos = promo_df[
            (promo_df["start_date"] <= txn_date) &
            (promo_df["end_date"] >= txn_date) &
            ((promo_df["target_segment"] == "All") | (promo_df["target_segment"] == seg))
        ]

        if len(active_promos) > 0 and np.random.random() < 0.40:
            promo = active_promos.sample(1).iloc[0]
            used_promo = promo["promotion_id"]
            if promo["promo_type"] == "percent_discount":
                discount_amount = round(subtotal * promo["discount_value"] / 100, 2)
            elif promo["promo_type"] == "fixed_discount":
                discount_amount = min(promo["discount_value"], subtotal)

        net_amount = subtotal - discount_amount

        transactions_list.append({
            "customer_id": c_id,
            "transaction_date": txn_date.strftime("%Y-%m-%d"),
            "subtotal": subtotal,
            "promo_used": used_promo,
            "discount": discount_amount,
            "net_amount": net_amount
        })

sales_df = pd.DataFrame(transactions_list)

# ==========================================
# 4. บันทึกไฟล์ทั้งหมดลงโฟลเดอร์ data/raw
# ==========================================
os.makedirs("data/raw", exist_ok=True)
customer_df.to_csv("data/raw/customer_master.csv", index=False)
promo_df.to_csv("data/raw/promotion_master.csv", index=False)
sales_df.to_csv("data/raw/sales_transaction.csv", index=False)

print("✅ สร้างข้อมูลและเซฟไฟล์ทับใหม่เรียบร้อยแล้ว!")
print(f"เช็กจำนวนลูกค้า: {customer_df.shape[0]} คน (ควรได้ 500)")
print(f"เช็กตารางยอดขาย: ได้ข้อมูลทั้งหมด {sales_df.shape[0]} รายการ")

"""ตรวจสอบไฟล์ที่ได้:"""

df = pd.read_csv("data/raw/customer_master.csv")
print(df.shape)         # (500, 6)
print(df.dtypes)        # ตรวจ data type ทุก column
print(df.isnull().sum()) # ตรวจ missing values
print(df.head())        # ดู 5 แถวแรก

# โหลดไฟล์ยอดขายมาตรวจสอบ
df_sales = pd.read_csv("data/raw/sales_transaction.csv")

print("ขนาดของตารางยอดขาย (แถว, คอลัมน์):", df_sales.shape)
print("\nตัวอย่างข้อมูลยอดขาย 5 แถวแรก:")
display(df_sales.head())